# Generated by Django 5.2.4 on 2025-07-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
